import type { Metadata } from "next";
import "../globals.css";
import LayoutClient from "../../components/LayoutClient";
import Providers from "../providers";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'tr' }, {locale: 'de'}];
}

export default function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { locale: string }
}) {
  const messages = await getMessages();
  return (
    <html lang={params.locale}>
      <body style={{ margin: 0, padding: 0 }}>
        <Providers messages={messages}>
          <LayoutClient children={children} locale={params.locale}/>
        </Providers>
      </body>
    </html>
  );
}
