import type { Metadata } from "next";
import "../globals.css";
import LayoutClient from "../../components/LayoutClient";
import Providers from "../providers";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}

export async function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'tr' }, {locale: 'de'}];
}

export default async function LocaleLayout({
  children,
  params
}: LayoutProps ) {
  const { locale } = await params;
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body style={{ margin: 0, padding: 0 }}>
        <Providers messages={messages}>
          <LayoutClient locale={locale}>
            {children}
          </LayoutClient>
        </Providers>
      </body>
    </html>
  );
}
